"""empty message

Revision ID: 10c0dcccaf0d
Revises: 4d8178dac5d9
Create Date: 2022-05-25 12:06:17.071640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10c0dcccaf0d'
down_revision = '4d8178dac5d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('species', sa.String(length=50), nullable=False),
    sa.Column('latin_name', sa.String(length=200), nullable=True),
    sa.Column('size_cm', sa.Integer(), nullable=True),
    sa.Column('diet', sa.String(length=255), nullable=True),
    sa.Column('lifespan', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('image', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Float(precision=2), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('animal')
    # ### end Alembic commands ###
